In [3]:
import pandas as pd
import os
import csv
from pathlib import Path
import datetime as dt

## LOAD/CLEAN ORIGINAL DATA SOURCE

In [4]:
file_to_load = "./Resources/Sale_Prices_City.csv"
sale_price_df = pd.read_csv(file_to_load, low_memory=False)
sale_price_df

,Unnamed: 0,RegionID,RegionName,StateName,SizeRank,2008-03,2008-04,2008-05,2008-06,2008-07,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,0,6181,New York,New York,1,NaN,NaN,NaN,NaN,NaN,...,563200.0,570500.0,572800.0,569900.0,560800.0,571500.0,575100.0,571700.0,568300.0,573600.0
1,1,12447,Los Angeles,California,2,507600.0,489600.0,463000.0,453100.0,438100.0,...,706800.0,711800.0,717300.0,714100.0,711900.0,718400.0,727100.0,738200.0,760200.0,NaN
2,2,39051,Houston,Texas,3,138400.0,135500.0,132200.0,131000.0,133400.0,...,209700.0,207400.0,207600.0,207000.0,211400.0,211500.0,217700.0,219200.0,223800.0,NaN
3,3,17426,Chicago,Illinois,4,325100.0,314800.0,286900.0,274600.0,268500.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
4,4,6915,San Antonio,Texas,5,130900.0,131300.0,131200.0,131500.0,131600.0,...,197100.0,198700.0,200200.0,200800.0,203400.0,203800.0,205400.0,205400.0,208300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723,3723,40400,Port Bolivar,Texas,3724,NaN,NaN,NaN,NaN,NaN,...,278400.0,254300.0,273200.0,286200.0,278100.0,285500.0,267200.0,302900.0,333700.0,330100.0
3724,3724,397820,Long Beach Township,New Jersey,3725,NaN,NaN,NaN,NaN,NaN,...,846300.0,912100.0,943700.0,897600.0,836000.0,839900.0,824100.0,839000.0,860600.0,NaN
3725,3725,37346,Beech Mountain,North Carolina,3726,NaN,NaN,NaN,NaN,NaN,...,191400.0,172700.0,195700.0,189500.0,166500.0,130900.0,139800.0,129400.0,124800.0,131000.0
3726,3726,34991,Corolla,North Carolina,3727,NaN,NaN,NaN,NaN,NaN,...,522400.0,521000.0,480000.0,430600.0,476400.0,560800.0,565400.0,514000.0,444200.0,NaN
3727,3727,52829,La Vernia,Texas,3728,NaN,NaN,NaN,NaN,NaN,...,337900.0,342900.0,358300.0,373100.0,375100.0,358600.0,356500.0,336700.0,340400.0,327000.0

In [5]:
clean_sale_df = sale_price_df.dropna()
clean_sale_df = clean_sale_df.drop(columns=['Unnamed: 0'], axis=1)
clean_sale_df

,RegionID,RegionName,StateName,SizeRank,2008-03,2008-04,2008-05,2008-06,2008-07,2008-08,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
3,17426,Chicago,Illinois,4,325100.0,314800.0,286900.0,274600.0,268500.0,264400.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
7,18959,Las Vegas,Nevada,8,244400.0,240100.0,234600.0,227200.0,218100.0,206900.0,...,266000.0,268200.0,268400.0,270400.0,272200.0,274400.0,277500.0,278900.0,283000.0,284700.0
9,38128,Dallas,Texas,10,148400.0,142300.0,150900.0,157300.0,164100.0,163400.0,...,300600.0,301100.0,301500.0,310100.0,314600.0,316900.0,307100.0,321500.0,315500.0,321700.0
18,10920,Columbus,Ohio,19,116000.0,112100.0,114900.0,113800.0,111900.0,108200.0,...,152600.0,154800.0,158500.0,157700.0,162900.0,166600.0,172700.0,175300.0,173600.0,177600.0
19,12455,Louisville,Kentucky,20,124800.0,123500.0,122100.0,121900.0,121500.0,122100.0,...,172700.0,175900.0,176000.0,173900.0,175400.0,174600.0,176600.0,170800.0,173100.0,176200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,27950,Wildwood,New Jersey,3649,268300.0,256500.0,265200.0,289400.0,305100.0,294300.0,...,260100.0,260000.0,267200.0,264100.0,263300.0,266200.0,275300.0,274000.0,264500.0,270200.0
3660,36173,Miramar Beach,Florida,3661,342200.0,362900.0,394800.0,434700.0,407400.0,364700.0,...,375700.0,384500.0,379300.0,374100.0,368200.0,370700.0,412500.0,408900.0,409000.0,379500.0
3680,21021,Vail,Arizona,3681,280700.0,281200.0,267000.0,258700.0,256600.0,253200.0,...,277600.0,277800.0,283100.0,286700.0,297000.0,297200.0,292100.0,275100.0,265400.0,269300.0
3689,25643,Longboat Key,Florida,3690,646800.0,613000.0,546400.0,602800.0,643800.0,696400.0,...,567400.0,554700.0,502000.0,495600.0,535300.0,557900.0,577100.0,557900.0,565600.0,579700.0
3703,48710,Arnold,California,3704,360700.0,342700.0,316500.0,332800.0,332300.0,315100.0,...,326500.0,317800.0,293100.0,281000.0,279100.0,279400.0,287100.0,305300.0,325600.0,345100.0

In [6]:
# export csv that we'll use to scrape location data
file_path = Path("./Resources/Sale_Prices_City_sample.csv")
clean_sale_df.to_csv(file_path, index=False)

### Build framework for properly transposed dataset

In [7]:
# getting ready to transpose data so its indexed by timeframe
# first, drop useless columns
time_df = clean_sale_df.drop(columns=["RegionName", "StateName", "SizeRank"])
time_df

,RegionID,2008-03,2008-04,2008-05,2008-06,2008-07,2008-08,2008-09,2008-10,2008-11,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
3,17426,325100.0,314800.0,286900.0,274600.0,268500.0,264400.0,267100.0,268400.0,259700.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
7,18959,244400.0,240100.0,234600.0,227200.0,218100.0,206900.0,194900.0,185100.0,175000.0,...,266000.0,268200.0,268400.0,270400.0,272200.0,274400.0,277500.0,278900.0,283000.0,284700.0
9,38128,148400.0,142300.0,150900.0,157300.0,164100.0,163400.0,157800.0,148100.0,142600.0,...,300600.0,301100.0,301500.0,310100.0,314600.0,316900.0,307100.0,321500.0,315500.0,321700.0
18,10920,116000.0,112100.0,114900.0,113800.0,111900.0,108200.0,106700.0,104700.0,100500.0,...,152600.0,154800.0,158500.0,157700.0,162900.0,166600.0,172700.0,175300.0,173600.0,177600.0
19,12455,124800.0,123500.0,122100.0,121900.0,121500.0,122100.0,120300.0,119700.0,114800.0,...,172700.0,175900.0,176000.0,173900.0,175400.0,174600.0,176600.0,170800.0,173100.0,176200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,27950,268300.0,256500.0,265200.0,289400.0,305100.0,294300.0,270100.0,269800.0,286800.0,...,260100.0,260000.0,267200.0,264100.0,263300.0,266200.0,275300.0,274000.0,264500.0,270200.0
3660,36173,342200.0,362900.0,394800.0,434700.0,407400.0,364700.0,342500.0,322200.0,344100.0,...,375700.0,384500.0,379300.0,374100.0,368200.0,370700.0,412500.0,408900.0,409000.0,379500.0
3680,21021,280700.0,281200.0,267000.0,258700.0,256600.0,253200.0,231500.0,228100.0,234100.0,...,277600.0,277800.0,283100.0,286700.0,297000.0,297200.0,292100.0,275100.0,265400.0,269300.0
3689,25643,646800.0,613000.0,546400.0,602800.0,643800.0,696400.0,744400.0,686100.0,655600.0,...,567400.0,554700.0,502000.0,495600.0,535300.0,557900.0,577100.0,557900.0,565600.0,579700.0
3703,48710,360700.0,342700.0,316500.0,332800.0,332300.0,315100.0,316700.0,322400.0,303800.0,...,326500.0,317800.0,293100.0,281000.0,279100.0,279400.0,287100.0,305300.0,325600.0,345100.0

In [8]:
# Transpose dataframe to make the date the index, with the RegionID's as the columns
time_transposed = time_df.transpose()
time_transposed.reset_index(drop = False, inplace = True)
time_transposed = time_transposed.rename(columns=time_transposed.iloc[0])
time_transposed = time_transposed.drop([0, 0])
time_transposed = time_transposed.rename(columns={"RegionID": 'DATE'})
time_transposed

,DATE,17426.0,18959.0,38128.0,10920.0,12455.0,13121.0,11093.0,41568.0,13373.0,...,21446.0,13837.0,24162.0,15959.0,26869.0,27950.0,36173.0,21021.0,25643.0,48710.0
1,2008-03,325100.0,244400.0,148400.0,116000.0,124800.0,222600.0,185800.0,382500.0,293000.0,...,101300.0,550300.0,306500.0,580700.0,242600.0,268300.0,342200.0,280700.0,646800.0,360700.0
2,2008-04,314800.0,240100.0,142300.0,112100.0,123500.0,214500.0,179800.0,380900.0,284600.0,...,105700.0,559500.0,304400.0,557600.0,229700.0,256500.0,362900.0,281200.0,613000.0,342700.0
3,2008-05,286900.0,234600.0,150900.0,114900.0,122100.0,201600.0,172100.0,382100.0,282900.0,...,108700.0,580600.0,281200.0,591700.0,224500.0,265200.0,394800.0,267000.0,546400.0,316500.0
4,2008-06,274600.0,227200.0,157300.0,113800.0,121900.0,194800.0,163500.0,382400.0,284700.0,...,122900.0,549100.0,271200.0,652800.0,217700.0,289400.0,434700.0,258700.0,602800.0,332800.0
5,2008-07,268500.0,218100.0,164100.0,111900.0,121500.0,190600.0,163700.0,386800.0,287000.0,...,130000.0,534000.0,252700.0,668800.0,217700.0,305100.0,407400.0,256600.0,643800.0,332300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,2019-11,264300.0,274400.0,316900.0,166600.0,174600.0,247400.0,445400.0,566400.0,432200.0,...,193100.0,620200.0,309100.0,808000.0,264100.0,266200.0,370700.0,297200.0,557900.0,279400.0
142,2019-12,270000.0,277500.0,307100.0,172700.0,176600.0,251100.0,435500.0,577600.0,431900.0,...,205200.0,631200.0,320800.0,839900.0,265200.0,275300.0,412500.0,292100.0,577100.0,287100.0
143,2020-01,281400.0,278900.0,321500.0,175300.0,170800.0,254800.0,435100.0,580100.0,435400.0,...,219700.0,566700.0,338400.0,736900.0,272300.0,274000.0,408900.0,275100.0,557900.0,305300.0
144,2020-02,302900.0,283000.0,315500.0,173600.0,173100.0,263500.0,436900.0,575700.0,435200.0,...,219400.0,601300.0,342600.0,682600.0,248800.0,264500.0,409000.0,265400.0,565600.0,325600.0
145,2020-03,309200.0,284700.0,321700.0,177600.0,176200.0,270500.0,442700.0,586100.0,439500.0,...,217900.0,538100.0,352300.0,632300.0,235100.0,270200.0,379500.0,269300.0,579700.0,345100.0

In [9]:
# convert month column to datetime format
time_transposed['DATE'] = pd.to_datetime(time_transposed['DATE'], infer_datetime_format=True)
# check the data types
time_transposed.dtypes

/var/folders/gm/c_xwwqf15t71b9pr19cpd2yw0000gn/T/ipykernel_10384/3627156618.py:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  time_transposed['DATE'] = pd.to_datetime(time_transposed['DATE'], infer_datetime_format=True)

DATE       datetime64[ns]
17426.0           float64
18959.0           float64
38128.0           float64
10920.0           float64
                ...
27950.0           float64
36173.0           float64
21021.0           float64
25643.0           float64
48710.0           float64
Length: 863, dtype: object

In [10]:
time_transposed

,DATE,17426.0,18959.0,38128.0,10920.0,12455.0,13121.0,11093.0,41568.0,13373.0,...,21446.0,13837.0,24162.0,15959.0,26869.0,27950.0,36173.0,21021.0,25643.0,48710.0
1,2008-03-01,325100.0,244400.0,148400.0,116000.0,124800.0,222600.0,185800.0,382500.0,293000.0,...,101300.0,550300.0,306500.0,580700.0,242600.0,268300.0,342200.0,280700.0,646800.0,360700.0
2,2008-04-01,314800.0,240100.0,142300.0,112100.0,123500.0,214500.0,179800.0,380900.0,284600.0,...,105700.0,559500.0,304400.0,557600.0,229700.0,256500.0,362900.0,281200.0,613000.0,342700.0
3,2008-05-01,286900.0,234600.0,150900.0,114900.0,122100.0,201600.0,172100.0,382100.0,282900.0,...,108700.0,580600.0,281200.0,591700.0,224500.0,265200.0,394800.0,267000.0,546400.0,316500.0
4,2008-06-01,274600.0,227200.0,157300.0,113800.0,121900.0,194800.0,163500.0,382400.0,284700.0,...,122900.0,549100.0,271200.0,652800.0,217700.0,289400.0,434700.0,258700.0,602800.0,332800.0
5,2008-07-01,268500.0,218100.0,164100.0,111900.0,121500.0,190600.0,163700.0,386800.0,287000.0,...,130000.0,534000.0,252700.0,668800.0,217700.0,305100.0,407400.0,256600.0,643800.0,332300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,2019-11-01,264300.0,274400.0,316900.0,166600.0,174600.0,247400.0,445400.0,566400.0,432200.0,...,193100.0,620200.0,309100.0,808000.0,264100.0,266200.0,370700.0,297200.0,557900.0,279400.0
142,2019-12-01,270000.0,277500.0,307100.0,172700.0,176600.0,251100.0,435500.0,577600.0,431900.0,...,205200.0,631200.0,320800.0,839900.0,265200.0,275300.0,412500.0,292100.0,577100.0,287100.0
143,2020-01-01,281400.0,278900.0,321500.0,175300.0,170800.0,254800.0,435100.0,580100.0,435400.0,...,219700.0,566700.0,338400.0,736900.0,272300.0,274000.0,408900.0,275100.0,557900.0,305300.0
144,2020-02-01,302900.0,283000.0,315500.0,173600.0,173100.0,263500.0,436900.0,575700.0,435200.0,...,219400.0,601300.0,342600.0,682600.0,248800.0,264500.0,409000.0,265400.0,565600.0,325600.0
145,2020-03-01,309200.0,284700.0,321700.0,177600.0,176200.0,270500.0,442700.0,586100.0,439500.0,...,217900.0,538100.0,352300.0,632300.0,235100.0,270200.0,379500.0,269300.0,579700.0,345100.0

In [11]:
# export transposed dataset to a csv
file_path = Path("./Resources/time_df_transposed.csv")
time_transposed.to_csv(file_path, index=False)